# Import Dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Data Collection and Preprocessing

In [ ]:
movie_dataset = pd.read_csv('/content/movies.csv')

In [ ]:
movie_dataset.head()

   index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [ ]:
# numbers of rows and columns in dataset
movie_dataset.shape

(4803, 24)

In [ ]:
#selecting the relevant features for recommendation
selected_features = ["genres"	, "keywords", "tagline","cast", "director"]
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [ ]:
# Replacing the null values with null string for selected features
for feature in selected_features:
  movie_dataset[feature] = movie_dataset[feature].fillna('')

In [ ]:
#checking for null values
movie_dataset.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [ ]:
# combining all the selected features
combined_features = movie_dataset['genres']+" " +movie_dataset['keywords']+" "+movie_dataset['tagline']+" "+movie_dataset['cast']+" "+movie_dataset['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [ ]:
# convert the textual data to vector feature or simple words in numerical values

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 124266 stored elements and shape (4803, 17318)>
  Coords	Values
  (0, 201)	0.07860022416510505
  (0, 274)	0.09021200873707368
  (0, 5274)	0.11108562744414445
  (0, 13599)	0.1036413987316636
  (0, 5437)	0.1036413987316636
  (0, 3678)	0.21392179219912877
  (0, 3065)	0.22208377802661425
  (0, 5836)	0.1646750903586285
  (0, 14378)	0.33962752210959823
  (0, 16587)	0.12549432354918996
  (0, 3225)	0.24960162956997736
  (0, 14271)	0.21392179219912877
  (0, 4945)	0.24025852494110758
  (0, 15261)	0.07095833561276566
  (0, 16998)	0.1282126322850579
  (0, 11192)	0.09049319826481456
  (0, 11503)	0.27211310056983656
  (0, 13349)	0.15021264094167086
  (0, 17007)	0.23643326319898797
  (0, 17290)	0.20197912553916567
  (0, 13319)	0.2177470539412484
  (0, 14064)	0.20596090415084142
  (0, 16668)	0.19843263965100372
  (0, 14608)	0.15150672398763912
  (0, 8756)	0.22709015857011816
  :	:
  (4801, 403)	0.17727585190343229
  (4801, 4835)	0.24713765026964
  (4801, 17266)	0.28860981849329476
  (4801, 13835)	0.27870029291200094
  (4801, 13175)	0.28860981849329476
  (4801, 17150)	0.3025765103586468
  (4801, 3511)	0.3025765103586468
  (4801, 13948)	0.3025765103586468
  (4801, 7269)	0.3025765103586468
  (4802, 11161)	0.17867407682173203
  (4802, 4518)	0.16784466610624255
  (4802, 2129)	0.3099656128577656
  (4802, 4980)	0.16078053641367315
  (4802, 6155)	0.18056463596934083
  (4802, 3436)	0.21753405888348784
  (4802, 4528)	0.19504460807622875
  (4802, 1316)	0.1960747079005741
  (4802, 12989)	0.1696476532191718
  (4802, 4371)	0.1538239182675544
  (4802, 6417)	0.21753405888348784
  (4802, 4608)	0.24002350969074696
  (4802, 2425)	0.24002350969074696
  (4802, 3654)	0.262512960498006
  (4802, 5367)	0.22969114490410403
  (4802, 6996)	0.5700048226105303

## Find Similarity Score

In [ ]:
#getting bthe similarity score using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.07219487 0.037733   ... 0.         0.         0.        ]
 [0.07219487 1.         0.03281499 ... 0.03575545 0.         0.        ]
 [0.037733   0.03281499 1.         ... 0.         0.05389661 0.        ]
 ...
 [0.         0.03575545 0.         ... 1.         0.         0.02651502]
 [0.         0.         0.05389661 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02651502 0.         1.        ]]

In [ ]:
print(similarity.shape)

(4803, 4803)

In [ ]:
# Getting the movie name from user
movie_name = input("Enter your Favourite movie name")

Enter your Favourite movie nameStranger things

In [ ]:
# Creating the list with all the movie names given in the dataset
list_all_of_the_titles = movie_dataset['title'].tolist()
print(list_all_of_the_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [ ]:
# finding the close match for the movie name given  by the user
find_close_match = difflib.get_close_matches(movie_name, list_all_of_the_titles)
print(find_close_match)

['Street Kings', 'Strangerland', 'Strange Wilderness']

In [ ]:
close_match = find_close_match[0]
print(close_match)

Street Kings

In [ ]:
 #find the index of the movie with title

index_of_the_movie = movie_dataset[movie_dataset.title == close_match]['index'].values[0]
print(index_of_the_movie)

2154

In [ ]:
#getting the list of similar movies
similarity_score  = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.006628368829871279)), (1, np.float64(0.005785253985053696)), (2, np.float64(0.03789625003894503)), (3, np.float64(0.03926881658956743)), (4, np.float64(0.006454357656621421)), (5, np.float64(0.006866471163794373)), (6, np.float64(0.0)), (7, np.float64(0.08551719125965795)), (8, np.float64(0.013923016287709377)), (9, np.float64(0.00653660015744028)), (10, np.float64(0.007455388958205723)), (11, np.float64(0.01979989343770087)), (12, np.float64(0.006767903031420249)), (13, np.float64(0.006110476243753357)), (14, np.float64(0.006585177448218473)), (15, np.float64(0.0)), (16, np.float64(0.08108847569889377)), (17, np.float64(0.006474284943243454)), (18, np.float64(0.006332882543511941)), (19, np.float64(0.005748114579103089)), (20, np.float64(0.006600858237887089)), (21, np.float64(0.03766256181791601)), (22, np.float64(0.0)), (23, np.float64(0.016769329144989773)), (24, np.float64(0.009464645135886587)), (25, np.float64(0.009653142083924388)), (26, np.float64(0.06805829479433181)), (27, np.float64(0.011670989305668684)), (28, np.float64(0.032208685541627965)), (29, np.float64(0.013404691864884324)), (30, np.float64(0.006680398403746821)), (31, np.float64(0.006514014386679505)), (32, np.float64(0.0)), (33, np.float64(0.04423141980836309)), (34, np.float64(0.0)), (35, np.float64(0.006979690584002759)), (36, np.float64(0.006289258208148492)), (37, np.float64(0.0)), (38, np.float64(0.028130098326496503)), (39, np.float64(0.006242353107300845)), (40, np.float64(0.0)), (41, np.float64(0.012341839679610245)), (42, np.float64(0.020918400670502206)), (43, np.float64(0.01302310642295976)), (44, np.float64(0.007144746853528414)), (45, np.float64(0.014710317988787606)), (46, np.float64(0.03644264125248525)), (47, np.float64(0.028810149209781335)), (48, np.float64(0.006791655294211544)), (49, np.float64(0.002848571506343736)), (50, np.float64(0.0064080417343647215)), (51, np.float64(0.0054409971687156946)), (52, np.float64(0.0059877905246179825)), (53, np.float64(0.044995256272794985)), (54, np.float64(0.0)), (55, np.float64(0.00697319252852587)), (56, np.float64(0.029186519372813552)), (57, np.float64(0.0)), (58, np.float64(0.047193433507672675)), (59, np.float64(0.006260140288518002)), (60, np.float64(0.00354985952642966)), (61, np.float64(0.006609073197891464)), (62, np.float64(0.019909760557444527)), (63, np.float64(0.0)), (64, np.float64(0.0)), (65, np.float64(0.03586104197455195)), (66, np.float64(0.0)), (67, np.float64(0.08386175945309203)), (68, np.float64(0.006215747906335323)), (69, np.float64(0.0029077773457813955)), (70, np.float64(0.006508000700803221)), (71, np.float64(0.008713339185331348)), (72, np.float64(0.09098510854712509)), (73, np.float64(0.0)), (74, np.float64(0.006658011260870644)), (75, np.float64(0.006273408054065721)), (76, np.float64(0.012918470920452785)), (77, np.float64(0.0033275644261562304)), (78, np.float64(0.0037528516176249956)), (79, np.float64(0.005988937027694071)), (80, np.float64(0.06609113899667363)), (81, np.float64(0.005110919341978624)), (82, np.float64(0.10010704710280986)), (83, np.float64(0.006825616769123596)), (84, np.float64(0.07651975729084838)), (85, np.float64(0.07211157291340743)), (86, np.float64(0.0)), (87, np.float64(0.07991022577349152)), (88, np.float64(0.025464010178815798)), (89, np.float64(0.0)), (90, np.float64(0.0)), (91, np.float64(0.006410839632538057)), (92, np.float64(0.020127891444189985)), (93, np.float64(0.02528447747953874)), (94, np.float64(0.02529670235995293)), (95, np.float64(0.003124853085623459)), (96, np.float64(0.022178429390958945)), (97, np.float64(0.03544289687078287)), (98, np.float64(0.00623363083350232)), (99, np.float64(0.10649482533686411)), (100, np.float64(0.0218550778125941)), (101, np.float64(0.007138748189763752)), (102, np.float64(0.0070260114842065164)), (103, np.float64(0.010309021331067519)), (104, np.float64(0.016567189862645628)), (105, np.float64(0.0)), (106, np.float64(0.07383038050189189)), (107, np.float64(0.007021406834244438)), (108, np.float64(0.01277715707788699)), (109, np.float64(0.0)), (110, np.float64(0.0)), (111, np.float64(0.06469312568991929)), (112, np.float64(0.00991967736111718)), (113, np.float64(0.013706647423639104)), (114, np.float64(0.0)), (115, np.float64(0.006379738340009165)), (116, np.float64(0.01457744031123831)), (117, np.float64(0.012319326677149875)), (118, np.float64(0.0)), (119, np.float64(0.030501914651741305)), (120, np.float64(0.03227592287682026)), (121, np.float64(0.00623079841866496)), (122, np.float64(0.047705741779388806)), (123, np.float64(0.09007356149587911)), (124, np.float64(0.017227884557626253)), (125, np.float64(0.08867488065814846)), (126, np.float64(0.02400556462838726)), (127, np.float64(0.04642751515386084)), (128, np.float64(0.006568585908972466)), (129, np.float64(0.026303047430274704)), (130, np.float64(0.017292583591080428)), (131, np.float64(0.007141441832624382)), (132, np.float64(0.0)), (133, np.float64(0.0)), (134, np.float64(0.012090233237739374)), (135, np.float64(0.00865308988479309)), (136, np.float64(0.0)), (137, np.float64(0.0)), (138, np.float64(0.006321096128317755)), (139, np.float64(0.011519998254519645)), (140, np.float64(0.01669980817445816)), (141, np.float64(0.0)), (142, np.float64(0.048628179470601156)), (143, np.float64(0.03220723937480538)), (144, np.float64(0.0)), (145, np.float64(0.002809277594120545)), (146, np.float64(0.02909766875756)), (147, np.float64(0.011536630091140147)), (148, np.float64(0.026141798403381607)), (149, np.float64(0.012367177086993815)), (150, np.float64(0.0063883532385429)), (151, np.float64(0.0064470374097415194)), (152, np.float64(0.00622734421356332)), (153, np.float64(0.07055813578555908)), (154, np.float64(0.05044946645013596)), (155, np.float64(0.051846642736959686)), (156, np.float64(0.008276894500703744)), (157, np.float64(0.010542582539319558)), (158, np.float64(0.02745133938338169)), (159, np.float64(0.006204759607462914)), (160, np.float64(0.0066652839747006936)), (161, np.float64(0.0)), (162, np.float64(0.008066021346232428)), (163, np.float64(0.024829806835742617)), (164, np.float64(0.029432299095134458)), (165, np.float64(0.011086011802454995)), (166, np.float64(0.01499621066476137)), (167, np.float64(0.010152584139133915)), (168, np.float64(0.006318226779368)), (169, np.float64(0.06440924335148976)), (170, np.float64(0.01058646327714053)), (171, np.float64(0.0)), (172, np.float64(0.0032690094687793957)), (173, np.float64(0.0)), (174, np.float64(0.005952094468207157)), (175, np.float64(0.0)), (176, np.float64(0.008816135965541167)), (177, np.float64(0.03623395709591594)), (178, np.float64(0.0)), (179, np.float64(0.07644411619816471)), (180, np.float64(0.03183083685422665)), (181, np.float64(0.0)), (182, np.float64(0.00636923545211498)), (183, np.float64(0.0068831412500058135)), (184, np.float64(0.0)), (185, np.float64(0.006179147267344111)), (186, np.float64(0.01939056388411402)), (187, np.float64(0.024650771258248775)), (188, np.float64(0.012985175362227173)), (189, np.float64(0.0037517142533341702)), (190, np.float64(0.0)), (191, np.float64(0.01295790451229145)), (192, np.float64(0.04809491370865704)), (193, np.float64(0.006983949613928589)), (194, np.float64(0.0)), (195, np.float64(0.0)), (196, np.float64(0.02106335650094869)), (197, np.float64(0.019720633608279154)), (198, np.float64(0.04563015457980596)), (199, np.float64(0.005897730238465732)), (200, np.float64(0.00640810657863288)), (201, np.float64(0.00666589186134156)), (202, np.float64(0.0)), (203, np.float64(0.03986150721986214)), (204, np.float64(0.022209350622219293)), (205, np.float64(0.016665348605691518)), (206, np.float64(0.006105603724871817)), (207, np.float64(0.00613390567198593)), (208, np.float64(0.006336122532648895)), (209, np.float64(0.013203894885742798)), (210, np.float64(0.04293788281739643)), (211, np.float64(0.0)), (212, np.float64(0.012195396306066433)), (213, np.float64(0.013987377654376435)), (214, np.float64(0.0034813450108181114)), (215, np.float64(0.07507182477289606)), (216, np.float64(0.009280064676855725)), (217, np.float64(0.012376313341409435)), (218, np.float64(0.015051143810635988)), (219, np.float64(0.007334505863105536)), (220, np.float64(0.0)), (221, np.float64(0.08572747009298019)), (222, np.float64(0.016782970435656082)), (223, np.float64(0.018266903412690865)), (224, np.float64(0.033890956367575276)), (225, np.float64(0.007383099205644894)), (226, np.float64(0.003876460729325534)), (227, np.float64(0.00653145553710492)), (228, np.float64(0.0062319770023799015)), (229, np.float64(0.006778866241459525)), (230, np.float64(0.0052045220283132)), (231, np.float64(0.0)), (232, np.float64(0.03436982697282251)), (233, np.float64(0.0054358446667831205)), (234, np.float64(0.019870440558075353)), (235, np.float64(0.0)), (236, np.float64(0.06515167778214069)), (237, np.float64(0.027419587525588984)), (238, np.float64(0.006087325296974998)), (239, np.float64(0.00859750010853162)), (240, np.float64(0.012992607370157486)), (241, np.float64(0.006417537073684004)), (242, np.float64(0.0070257981214078375)), (243, np.float64(0.006488156725454267)), (244, np.float64(0.01365378670523994)), (245, np.float64(0.011050392714447146)), (246, np.float64(0.009328604578309457)), (247, np.float64(0.014599105791893868)), (248, np.float64(0.016969507782283545)), (249, np.float64(0.006191561241638657)), (250, np.float64(0.0031321057086611225)), (251, np.float64(0.020498987674791556)), (252, np.float64(0.016335978573395422)), (253, np.float64(0.016841762006390773)), (254, np.float64(0.0)), (255, np.float64(0.0)), (256, np.float64(0.0)), (257, np.float64(0.04070339790943384)), (258, np.float64(0.0)), (259, np.float64(0.011376463187203135)), (260, np.float64(0.0065340160527113935)), (261, np.float64(0.014635665036147126)), (262, np.float64(0.006470984234143428)), (263, np.float64(0.006443887608079293)), (264, np.float64(0.0032168706307173114)), (265, np.float64(0.0)), (266, np.float64(0.006699641071031001)), (267, np.float64(0.02541976920393848)), (268, np.float64(0.08222486593700648)), (269, np.float64(0.012054540809470035)), (270, np.float64(0.003663040953117079)), (271, np.float64(0.014017881686300724)), (272, np.float64(0.01997894883742966)), (273, np.float64(0.0209497365257265)), (274, np.float64(0.010739722064394195)), (275, np.float64(0.012076184908527611)), (276, np.float64(0.019474446281338487)), (277, np.float64(0.012789140287181484)), (278, np.float64(0.01126611882105993)), (279, np.float64(0.013672625560467624)), (280, np.float64(0.012503868750731013)), (281, np.float64(0.012286552658337576)), (282, np.float64(0.011440358453894718)), (283, np.float64(0.04571486143872651)), (284, np.float64(0.0)), (285, np.float64(0.014744450169780987)), (286, np.float64(0.01627288143271819)), (287, np.float64(0.0033854702023177253)), (288, np.float64(0.004104648763564387)), (289, np.float64(0.01286963722869096)), (290, np.float64(0.013192637309388293)), (291, np.float64(0.011556038790330934)), (292, np.float64(0.005420324652256093)), (293, np.float64(0.0)), (294, np.float64(0.02068630752854521)), (295, np.float64(0.012152702227462672)), (296, np.float64(0.006928023905076954)), (297, np.float64(0.016446127786793358)), (298, np.float64(0.013499937730408411)), (299, np.float64(0.07300632061407103)), (300, np.float64(0.010602503516801531)), (301, np.float64(0.00350305004937919)), (302, np.float64(0.0)), (303, np.float64(0.016245921862752803)), (304, np.float64(0.006236642678681019)), (305, np.float64(0.013434014778969062)), (306, np.float64(0.0)), (307, np.float64(0.012392428091796047)), (308, np.float64(0.018991296495797214)), (309, np.float64(0.0)), (310, np.float64(0.034896021073727704)), (311, np.float64(0.01379897060224846)), (312, np.float64(0.014187999316042275)), (313, np.float64(0.0)), (314, np.float64(0.0344322637972777)), (315, np.float64(0.005837697604105698)), (316, np.float64(0.013185737856559066)), (317, np.float64(0.0031069238373090968)), (318, np.float64(0.0)), (319, np.float64(0.00701870173501624)), (320, np.float64(0.07852417203835096)), (321, np.float64(0.0)), (322, np.float64(0.0549506212997732)), (323, np.float64(0.03039294505132409)), (324, np.float64(0.0)), (325, np.float64(0.054669600065802064)), (326, np.float64(0.003411872514191974)), (327, np.float64(0.003576276051111783)), (328, np.float64(0.0)), (329, np.float64(0.006487212341563097)), (330, np.float64(0.0066580053983128695)), (331, np.float64(0.0)), (332, np.float64(0.010405066563061026)), (333, np.float64(0.008328056325956238)), (334, np.float64(0.011963372260987546)), (335, np.float64(0.016085601232645956)), (336, np.float64(0.05010783392008867)), (337, np.float64(0.008374782965032915)), (338, np.float64(0.0)), (339, np.float64(0.05166829623695913)), (340, np.float64(0.021175081481642582)), (341, np.float64(0.018476204289867112)), (342, np.float64(0.006033132020902996)), (343, np.float64(0.0)), (344, np.float64(0.026650247749966632)), (345, np.float64(0.04645929553291254)), (346, np.float64(0.008526812913499679)), (347, np.float64(0.0)), (348, np.float64(0.0)), (349, np.float64(0.003197482620870539)), (350, np.float64(0.03400096260862583)), (351, np.float64(0.04993822514157397)), (352, np.float64(0.0)), (353, np.float64(0.005389195441131302)), (354, np.float64(0.03155601270898645)), (355, np.float64(0.01339078982431357)), (356, np.float64(0.01657798450278161)), (357, np.float64(0.003426306796418445)), (358, np.float64(0.0)), (359, np.float64(0.0)), (360, np.float64(0.009277029056637628)), (361, np.float64(0.00644768694707585)), (362, np.float64(0.027940503470440067)), (363, np.float64(0.011877044335646528)), (364, np.float64(0.005397422737497583)), (365, np.float64(0.0030692995025924834)), (366, np.float64(0.01124171744464008)), (367, np.float64(0.03568818038975273)), (368, np.float64(0.0)), (369, np.float64(0.010312796705974521)), (370, np.float64(0.0164225344893903)), (371, np.float64(0.010084861866410211)), (372, np.float64(0.02090657228229139)), (373, np.float64(0.0)), (374, np.float64(0.0)), (375, np.float64(0.017452650799354288)), (376, np.float64(0.09832569210319955)), (377, np.float64(0.01417563602161419)), (378, np.float64(0.008767566467175239)), (379, np.float64(0.005605002360567321)), (380, np.float64(0.0030441187438719833)), (381, np.float64(0.008073604240312386)), (382, np.float64(0.03550413454336911)), (383, np.float64(0.009361547628748189)), (384, np.float64(0.022284541972005256)), (385, np.float64(0.030461087245712212)), (386, np.float64(0.016810448632678165)), (387, np.float64(0.012714305576122003)), (388, np.float64(0.05385654915106164)), (389, np.float64(0.012469721154483693)), (390, np.float64(0.013468976645718441)), (391, np.float64(0.0)), (392, np.float64(0.031896240831378396)), (393, np.float64(0.03058364512528117)), (394, np.float64(0.006653685921716772)), (395, np.float64(0.0)), (396, np.float64(0.01713235774629652)), (397, np.float64(0.0)), (398, np.float64(0.01550893439097695)), (399, np.float64(0.0)), (400, np.float64(0.0058111763869060215)), (401, np.float64(0.0)), (402, np.float64(0.01253884881435701)), (403, np.float64(0.006149957349755058)), (404, np.float64(0.002526021008266239)), (405, np.float64(0.03616918076041602)), (406, np.float64(0.07801733531734059)), (407, np.float64(0.0030221401702750094)), (408, np.float64(0.0164880247811482)), (409, np.float64(0.0019572289559563415)), (410, np.float64(0.0031607986450583455)), (411, np.float64(0.0501848621881503)), (412, np.float64(0.011827482445693312)), (413, np.float64(0.0)), (414, np.float64(0.009157763336841295)), (415, np.float64(0.017053601911497462)), (416, np.float64(0.015716681003429465)), (417, np.float64(0.0)), (418, np.float64(0.0)), (419, np.float64(0.0)), (420, np.float64(0.0)), (421, np.float64(0.03324792330304899)), (422, np.float64(0.0)), (423, np.float64(0.0)), (424, np.float64(0.012562054023991477)), (425, np.float64(0.01398841534125346)), (426, np.float64(0.0)), (427, np.float64(0.0)), (428, np.float64(0.017002466245827543)), (429, np.float64(0.0)), (430, np.float64(0.04623331467135492)), (431, np.float64(0.0)), (432, np.float64(0.009819665076224915)), (433, np.float64(0.024371109393898062)), (434, np.float64(0.023905386519130337)), (435, np.float64(0.013809668175045347)), (436, np.float64(0.0349489144098364)), (437, np.float64(0.014165266432395147)), (438, np.float64(0.09646451583894593)), (439, np.float64(0.010533436600719094)), (440, np.float64(0.003204904343296205)), (441, np.float64(0.03888359658087731)), (442, np.float64(0.019058299788977547)), (443, np.float64(0.0)), (444, np.float64(0.016834333950345143)), (445, np.float64(0.0)), (446, np.float64(0.021503150608032307)), (447, np.float64(0.013978821816704748)), (448, np.float64(0.01858025591088042)), (449, np.float64(0.011723336732802)), (450, np.float64(0.0)), (451, np.float64(0.0060171445312147236)), (452, np.float64(0.0028925580133253265)), (453, np.float64(0.016797805322528014)), (454, np.float64(0.07968044354238037)), (455, np.float64(0.015769606060409086)), (456, np.float64(0.08000795480777201)), (457, np.float64(0.019240034783250155)), (458, np.float64(0.0)), (459, np.float64(0.0)), (460, np.float64(0.0)), (461, np.float64(0.0)), (462, np.float64(0.009340452717236982)), (463, np.float64(0.003486794223843886)), (464, np.float64(0.0)), (465, np.float64(0.0)), (466, np.float64(0.00722007646194125)), (467, np.float64(0.007430047112794558)), (468, np.float64(0.051641532318419885)), (469, np.float64(0.00597662631979849)), (470, np.float64(0.0031996394574700386)), (471, np.float64(0.0)), (472, np.float64(0.012306996856334714)), (473, np.float64(0.0)), (474, np.float64(0.003225982199362328)), (475, np.float64(0.054315093802319095)), (476, np.float64(0.013055133376475703)), (477, np.float64(0.009059290870031675)), (478, np.float64(0.07448255285889757)), (479, np.float64(0.0)), (480, np.float64(0.09042160644791117)), (481, np.float64(0.0)), (482, np.float64(0.002957455657371699)), (483, np.float64(0.017842462013793733)), (484, np.float64(0.0029697613748323826)), (485, np.float64(0.03442384297888358)), (486, np.float64(0.006309234284849749)), (487, np.float64(0.010979630596873197)), (488, np.float64(0.0)), (489, np.float64(0.03910881916216053)), (490, np.float64(0.0659362503736183)), (491, np.float64(0.04463202109453827)), (492, np.float64(0.01609809606799435)), (493, np.float64(0.003461833973500461)), (494, np.float64(0.0030140329541627794)), (495, np.float64(0.006594768750179076)), (496, np.float64(0.0)), (497, np.float64(0.017898717079492015)), (498, np.float64(0.0)), (499, np.float64(0.0)), (500, np.float64(0.1043267141648353)), (501, np.float64(0.0)), (502, np.float64(0.004757955076956505)), (503, np.float64(0.005874647609355387)), (504, np.float64(0.019726403426093154)), (505, np.float64(0.012325597534904016)), (506, np.float64(0.0)), (507, np.float64(0.006427179288573313)), (508, np.float64(0.00658598657043593)), (509, np.float64(0.03136359556784381)), (510, np.float64(0.04386289037425839)), (511, np.float64(0.038629531655452416)), (512, np.float64(0.023376542310083064)), (513, np.float64(0.021390222627212675)), (514, np.float64(0.0)), (515, np.float64(0.0)), (516, np.float64(0.0)), (517, np.float64(0.005859034804847308)), (518, np.float64(0.02272802451754863)), (519, np.float64(0.03264984520836121)), (520, np.float64(0.0)), (521, np.float64(0.0035787275668114705)), (522, np.float64(0.019871475057842408)), (523, np.float64(0.03234129470385774)), (524, np.float64(0.003340814965873392)), (525, np.float64(0.005825496846301497)), (526, np.float64(0.003647632139506852)), (527, np.float64(0.007938056550171907)), (528, np.float64(0.012013138737028984)), (529, np.float64(0.008891311455211371)), (530, np.float64(0.01388796733195485)), (531, np.float64(0.006046205037983344)), (532, np.float64(0.0)), (533, np.float64(0.0)), (534, np.float64(0.02906103357011858)), (535, np.float64(0.05870604980736568)), (536, np.float64(0.0031651001859832645)), (537, np.float64(0.04731918393093247)), (538, np.float64(0.046969251469025

In [ ]:
len(similarity_score)

4803

In [ ]:
# Sorting the movies base on their similarity score
sorted_similar_movies = sorted(similarity_score , key = lambda x:x[1] , reverse = True)
print(sorted_similar_movies)

[(2154, np.float64(1.0000000000000002)), (1592, np.float64(0.2131280195017709)), (2545, np.float64(0.19598760732072565)), (1024, np.float64(0.18408120469110834)), (747, np.float64(0.1778164689119403)), (2072, np.float64(0.17274313496486834)), (4067, np.float64(0.16260907834753718)), (574, np.float64(0.15405413985231894)), (2924, np.float64(0.15186188889894175)), (1662, np.float64(0.14144025567542143)), (1854, np.float64(0.13739159604503723)), (4159, np.float64(0.13291385571694866)), (1448, np.float64(0.13027904398171436)), (1010, np.float64(0.1276142274139459)), (2007, np.float64(0.12710613347416555)), (1076, np.float64(0.12526116446504765)), (2548, np.float64(0.12216165268342954)), (2741, np.float64(0.12140634229970912)), (716, np.float64(0.12134912183932386)), (1052, np.float64(0.11963486171083601)), (2764, np.float64(0.1166995888372529)), (2557, np.float64(0.11490708906174649)), (1597, np.float64(0.11203991594928561)), (1178, np.float64(0.11197353205740664)), (3516, np.float64(0.10849928076676842)), (1908, np.float64(0.10809753316722802)), (1485, np.float64(0.10789292152528324)), (99, np.float64(0.10649482533686411)), (2453, np.float64(0.10613273092974264)), (2111, np.float64(0.10531986764768271)), (4602, np.float64(0.10466325396064356)), (500, np.float64(0.1043267141648353)), (2502, np.float64(0.10366178482054492)), (1905, np.float64(0.10345563414793094)), (1020, np.float64(0.10302938260740399)), (1469, np.float64(0.10189852097384033)), (3527, np.float64(0.10088734346177018)), (3165, np.float64(0.10016496650526863)), (82, np.float64(0.10010704710280986)), (2070, np.float64(0.09951611154512678)), (1109, np.float64(0.09898262877638735)), (3734, np.float64(0.09884883576000253)), (376, np.float64(0.09832569210319955)), (850, np.float64(0.09791728139208389)), (1019, np.float64(0.09738887743616437)), (878, np.float64(0.09686262256742814)), (4099, np.float64(0.09652479968526607)), (438, np.float64(0.09646451583894593)), (1547, np.float64(0.09567223229285507)), (544, np.float64(0.09533025256659922)), (2235, np.float64(0.09512729528365116)), (1653, np.float64(0.0949604534492329)), (1167, np.float64(0.09462816343031485)), (2225, np.float64(0.09450363428375867)), (1542, np.float64(0.09444387977367721)), (801, np.float64(0.09435181674782217)), (763, np.float64(0.09388418310438848)), (2682, np.float64(0.09322227003309218)), (2086, np.float64(0.0931965260536093)), (3796, np.float64(0.0931052581946746)), (1377, np.float64(0.0927161648405411)), (2432, np.float64(0.09248035636473162)), (2492, np.float64(0.09184359612179357)), (72, np.float64(0.09098510854712509)), (3287, np.float64(0.09074948167478616)), (4433, np.float64(0.09056140685156613)), (480, np.float64(0.09042160644791117)), (2674, np.float64(0.09028919310620347)), (123, np.float64(0.09007356149587911)), (3445, np.float64(0.08991199715064127)), (3088, np.float64(0.08959895340406832)), (1241, np.float64(0.08948911736524044)), (3468, np.float64(0.0893687266589599)), (125, np.float64(0.08867488065814846)), (3033, np.float64(0.0881791881264852)), (932, np.float64(0.08788182332838132)), (2198, np.float64(0.08692469862897778)), (634, np.float64(0.08690745438725397)), (3467, np.float64(0.08684243487145771)), (2508, np.float64(0.08575844381467872)), (221, np.float64(0.08572747009298019)), (1837, np.float64(0.08561101679336905)), (4015, np.float64(0.08552104520896178)), (7, np.float64(0.08551719125965795)), (1792, np.float64(0.08520123935907789)), (2614, np.float64(0.08502872372045561)), (67, np.float64(0.08386175945309203)), (772, np.float64(0.08375956113674382)), (860, np.float64(0.08317813128615384)), (1517, np.float64(0.08280904664653033)), (3274, np.float64(0.08251530173325135)), (268, np.float64(0.08222486593700648)), (16, np.float64(0.08108847569889377)), (4574, np.float64(0.08108312478808796)), (1699, np.float64(0.08070184190804945)), (1426, np.float64(0.08047829668676809)), (4069, np.float64(0.08035780564892087)), (1781, np.float64(0.08024076845061029)), (3250, np.float64(0.08022531034254843)), (3773, np.float64(0.08005738813645094)), (456, np.float64(0.08000795480777201)), (87, np.float64(0.07991022577349152)), (3198, np.float64(0.07982304602772786)), (454, np.float64(0.07968044354238037)), (1957, np.float64(0.07960709542568314)), (1495, np.float64(0.07959828317604878)), (1412, np.float64(0.07959045410076548)), (831, np.float64(0.07940798059177699)), (4098, np.float64(0.07873511657348697)), (1204, np.float64(0.07872966236622567)), (320, np.float64(0.07852417203835096)), (2744, np.float64(0.07842288509336245)), (2127, np.float64(0.07816277697406127)), (406, np.float64(0.07801733531734059)), (948, np.float64(0.07798436652697799)), (1882, np.float64(0.07794694479274845)), (1199, np.float64(0.07790984822795005)), (2197, np.float64(0.07768049092750806)), (1382, np.float64(0.07764125952450693)), (2689, np.float64(0.07752023178085973)), (665, np.float64(0.07726760895174051)), (4130, np.float64(0.07699909128888616)), (3883, np.float64(0.07677689641369133)), (4164, np.float64(0.07656663092747529)), (84, np.float64(0.07651975729084838)), (179, np.float64(0.07644411619816471)), (1686, np.float64(0.07623510024719585)), (2481, np.float64(0.07537150205351362)), (215, np.float64(0.07507182477289606)), (478, np.float64(0.07448255285889757)), (3694, np.float64(0.07446285019243912)), (4129, np.float64(0.07428972086799437)), (1518, np.float64(0.07418526500129782)), (2611, np.float64(0.07418040812779836)), (106, np.float64(0.07383038050189189)), (2026, np.float64(0.07377513091828877)), (1641, np.float64(0.07376585209735807)), (3437, np.float64(0.07369512093573809)), (2304, np.float64(0.07359826968942847)), (3073, np.float64(0.07350018659684314)), (2399, np.float64(0.07335782793982489)), (968, np.float64(0.07317966036612557)), (3309, np.float64(0.07310765044211882)), (299, np.float64(0.07300632061407103)), (893, np.float64(0.07300191706335275)), (1339, np.float64(0.07293181909156166)), (1575, np.float64(0.07291967225266903)), (2818, np.float64(0.07271653354464107)), (85, np.float64(0.07211157291340743)), (4136, np.float64(0.07187685538662505)), (2991, np.float64(0.07115996264479385)), (4066, np.float64(0.07104312997511389)), (2727, np.float64(0.07089184599469942)), (4507, np.float64(0.07085748778660925)), (739, np.float64(0.07067895932475189)), (153, np.float64(0.07055813578555908)), (973, np.float64(0.0705090254480848)), (542, np.float64(0.07044910233218851)), (2138, np.float64(0.06988356109354217)), (2282, np.float64(0.06984659515333413)), (2558, np.float64(0.06982466661847164)), (1892, np.float64(0.06928819176791925)), (1826, np.float64(0.06870875544048258)), (1728, np.float64(0.06868125438393485)), (2695, np.float64(0.06841031340537562)), (562, np.float64(0.06832642990348045)), (3700, np.float64(0.06816802004769593)), (26, np.float64(0.06805829479433181)), (2893, np.float64(0.06772827985620175)), (4408, np.float64(0.06726361980081211)), (727, np.float64(0.06703276651371014)), (4795, np.float64(0.06683411759012571)), (1617, np.float64(0.06652512361831536)), (1911, np.float64(0.06647211878826925)), (80, np.float64(0.06609113899667363)), (2931, np.float64(0.06593816134875272)), (490, np.float64(0.0659362503736183)), (1898, np.float64(0.065694446505922)), (3153, np.float64(0.06533697252504275)), (236, np.float64(0.06515167778214069)), (4146, np.float64(0.0650338094834111)), (695, np.float64(0.06502536764428185)), (1961, np.float64(0.06501078678486809)), (1664, np.float64(0.06492907891815747)), (2018, np.float64(0.0648860095048818)), (111, np.float64(0.06469312568991929)), (619, np.float64(0.06444101194564193)), (169, np.float64(0.06440924335148976)), (615, np.float64(0.06430587780050154)), (3903, np.float64(0.06428198230717896)), (965, np.float64(0.06399844472083353)), (1815, np.float64(0.06384152323410038)), (919, np.float64(0.0632277153352383)), (1619, np.float64(0.06264598353722513)), (1397, np.float64(0.06260660249735445)), (989, np.float64(0.06250499429741793)), (1386, np.float64(0.06225534770231152)), (1275, np.float64(0.06220457860565464)), (717, np.float64(0.06218518738140542)), (2418, np.float64(0.061996544503245585)), (1164, np.float64(0.061945464423134936)), (2075, np.float64(0.06169703899791579)), (756, np.float64(0.061585242999604425)), (3346, np.float64(0.06154390393544671)), (1146, np.float64(0.06094441725447811)), (3255, np.float64(0.06051290877238346)), (1131, np.float64(0.06028351891167772)), (3040, np.float64(0.06010499776858682)), (4326, np.float64(0.06005844817244775)), (2518, np.float64(0.0600137622624312)), (2678, np.float64(0.05968176600607325)), (1219, np.float64(0.059565069061611554)), (3859, np.float64(0.05942464660795151)), (2596, np.float64(0.058935716564638425)), (2074, np.float64(0.058868084481104574)), (535, np.float64(0.05870604980736568)), (559, np.float64(0.05821690619495865)), (3655, np.float64(0.05818831118387212)), (2028, np.float64(0.05808888722767281)), (4014, np.float64(0.05807797971937147)), (1106, np.float64(0.05730638100458227)), (2336, np.float64(0.057275451513095876)), (4441, np.float64(0.057272779209057455)), (4105, np.float64(0.05716068812760704)), (1479, np.float64(0.056728626079565414)), (1844, np.float64(0.056726703236903694)), (1054, np.float64(0.056367189181876706)), (1830, np.float64(0.05633428754393481)), (4281, np.float64(0.05624726579956225)), (4675, np.float64(0.05605991797781143)), (2901, np.float64(0.056012699129961006)), (4472, np.float64(0.05573305217548765)), (737, np.float64(0.055714508302476096)), (2767, np.float64(0.05565988904648789)), (1174, np.float64(0.05563179075857591)), (3104, np.float64(0.05557917346032479)), (3267, np.float64(0.055299823087972336)), (4685, np.float64(0.05525807482164948)), (1314, np.float64(0.055192935533121476)), (1925, np.float64(0.055153962300852274)), (4402, np.float64(0.05511584911237474)), (2242, np.float64(0.05501430084308564)), (322, np.float64(0.0549506212997732)), (4609, np.float64(0.05473431107500513)), (1503, np.float64(0.054723664734973546)), (3815, np.float64(0.05468517912582077)), (325, np.float64(0.054669600065802064)), (1286, np.float64(0.054519511457973374)), (1338, np.float64(0.05449532311500978)), (1773, np.float64(0.05444679388162606)), (660, np.float64(0.054384690367935945)), (475, np.float64(0.054315093802319095)), (2889, np.float64(0.05425676228083601)), (388, np.float64(0.05385654915106164)), (1144, np.float64(0.053620032441435025)), (950, np.float64(0.05360241834540295)), (2777, np.float64(0.05320265565131718)), (3508, np.float64(0.053168015515505616)), (2135, np.float64(0.05311587106985566)), (4335, np.float64(0.05293206231915473)), (3062, np.float64(0.05283561161676892)), (2207, np.float64(0.052797137995414044)), (3347, np.float64(0.05263308939548922)), (1066, np.float64(0.05261945826551091)), (1986, np.float64(0.05238932927506927)), (3606, np.float64(0.05228279208356085)), (3664, np.float64(0.052164593536696856)), (2512, np.float64(0.052146283233843536)), (3628, np.float64(0.05213737994345514)), (1756, np.float64(0.05204560765858429)), (1569, np.float64(0.05200662698224432)), (155, np.float64(0.051846642736959686)), (2885, np.float64(0.05181969840589959)), (3698, np.float64(0.051744989663227874)), (339, np.float64(0.05166829623695913)), (468, np.float64(0.051641532318419885)), (3234, np.float64(0.051226113281108626)), (1444, np.float64(0.05120535264204167)), (3899, np.float64(0.051202334320269265)), (1051, np.float64(0.05109648277360557)), (606, np.float64(0.05099479378305406)), (1253, np.float64(0.05082008195896922)), (2046, np.float64(0.05070833759128669)), (2388, np.float64(0.05069738134198691)), (154, np.float64(0.05044946645013596)), (642, np.float64(0.05042558202162731)), (1993, np.float64(0.050423226449354625)), (1870, np.float64(0.050366361342290604)), (2715, np.float64(0.05034261905007485)), (4695, np.float64(0.05023870954601728)), (2780, np.float64(0.05020737929432109)), (411, np.float64(0.0501848621881503)), (336, np.float64(0.05010783392008867)), (1139, np.float64(0.04996258562902244)), (351, np.float64(0.04993822514157397)), (3631, np.float64(0.049800409518084794)), (613, np.float64(0.049759872578564644)), (4442, np.float64(0.04940861961425725)), (2609, np.float64(0.04936785770842313)), (2851, np.float64(0.04934576288360556)), (3075, np.float64(0.04933915850196155)), (1800, np.float64(0.04869426419176031)), (142, np.float64(0.048628179470601156)), (589, np.float64(0.04858926796304309)), (1644, np.float64(0.04858607539385065)), (3483, np.float64(0.048422598324133356)), (2751, np.float64(0.04823758058189024)), (1764, np.float64(0.04812365368975833)), (192, np.float64(0.04809491370865704)), (3306, np.float64(0.0478209642581213)), (787, np.float64(0.047777032262208904)), (4005, np.float64(0.047737388090821786)), (122, np.float64(0.047705741779388806)), (2934, np.float64(0.0476944119691219)), (3372, np.float64(0.04766027805074123)), (3414, np.float64(0.047643275748836415)), (599, np.float64(0.047607251952475026)), (4415, np.float64(0.04760606007520608)), (2834, np.float64(0.047544942163129315)), (537, np.float64(0.04731918393093247)), (3575, np.float64(0.04728269178494589)), (1670, np.float64(0.04719904071130376)), (58, np.float64(0.047193433507672675)), (2264, np.float64(0.04717778655252474)), (1678, np.float64(0.04700858305723011)), (538, np.float64(0.046969251469025614)), (2544, np.float64(0.04686986892985537)), (1834, np.float64(0.04682758151781502)), (1488, np.float64(0.04654660878523324)), (982, np.float64(0.04645966931750235)), (345, np.float64(0.04645929553291254)), (127, np.float64(0.04642751515386084)), (3242, np.float64(0.04634793463842093)), (1235, np.float64(0.046246190524699055)), (430, np.float64(0.04623331467135492)), (1946, np.float64(0.04620212866799913)), (1700, np.float64(0.045879556411755465)), (1177, np.float64(0.04586309126386427)), (2997, np.float64(0.04576789249968492)), (4201, np.float64(0.04571640560211963)), (283, np.float64(0.04571486143872651)), (731, np.float64(0.0456976013931902)), (2273, np.float64(0.04568318967086899)), (198, np.float64(0.04563015457980596)), (871, np.float64(0.04561582649793535)), (754, np.float64(0.04558981797635484)), (4799, np.float64(0.0455487361237687)), (1502, np.float64(0.04552840047051352)), (1196, np.float64(0.04544346434405948)), (4529, np.float64(0.04521134271430729)), (3128, np.float64(0.045204289386090946)), (1860, np.float64(0.04510610527400748)), (53, np.float64(0.044995256272794985)), (2567, np.float64(0.04498731482422946)), (2632, np.float64(0.0449327720710067)), (4541, np.float64(0.044685368904774835)), (491, np.float64(0.04463202109453827)), (4711, np.float64(0.044544325573068914)), (3962, np.float64(0.04453815907872711)), (947, np.float64(0.04443813101192805)), (1041, np.float64(0.04442880498643431)), (4670, np.float64(0.044346682570370895)), (1153, np.float64(0.04433636821796065)), (33, np.float64(0.04423141980836309)), (2471, np.float64(0.04414517590797125)), (2543, np.float64(0.04389840676428161)), (510, np.float64(0.04386289037425839)), (1422, np.float64(0.043722901211443635)), (4083, np.float64(0.04366445115818997)), (1803, np.float64(0.04353605654682939)), (2948, np.float64(0.043178660749858225)), (2364, np.float64(0.043118435578559135)), (3834, np.float64(0.04311515450883603)), (3592, np.float64(0.043051620344451105)), (210, np.float64(0.04293788281739643)), (3195, np.float64(0.04284028810330448)), (2955, np.float64(0.04278826350274991)), (4337, np.float64(0.04276357331988673)), (1334, np.float64(0.042549448721726224)), (863, np.float64(0.04251481602554328)), (3081, np.float64(0.04238656093237661)), (3438, np.float64(0.04203789448638048)), (3397, np.float64(0.04197895858696424)), (3074, np.float64(0.04196624097109881)), (4001, np.float64(0.041834664966807864)), (974, np.float64(0.04177707750737919)), (1114, np.float64(0.04168317518883302)), (4084, np.float64(0.041628936467667514)), (3518, np.float64(0.04161062071832128)), (4580, np.float64(0.04160228498201367)), (3111, np.float64(0.04146173759320415)), (2440, np.float64(0.04134981596081008)), (4265, np.float64(0.04133621984129007)), (875, np.float64(0.04126576036193765)), (728, np.float64(0.041232066650704766)), (1467, np.float64(0.041201846228922236)), (2126, np.float64(0.041112954973249266)), (2345, np.float64(0.04110939093930008)), (2941, np.float64(0.041026764417165816)), (1082, np.float64(0.04092521707845272)), (1785, np.float64(0.04087106049752886)), (1281, np.float64(0.04070971132778275)), (257, np.float64(0.04070339790943384)), (3541, np.float64(0.04030617986719537)), (1770, np.float64(0.04028628069611203)), (3430, np.float64(0.04026696731034084)), (2071, np.float64(0.040191394216177324)), (2250, np.float64(0.040183033339247345)), (1972, np.float64(0.040140555383023774)), (2489, np.float64(0.040113267121049394)), (1225, np.float64(0.04009259868146945)), (1100, np.float64(0.04005646444524128)), (561, np.float64(0.039950090654689796)), (4139, np.float64(0.03994642871190135)), (203, np.float64(0.03986150721986214)), (1880, np.float64(0.03981750366174017)), (2175, np.float64(0.039728294635685495)), (608, np.float64(0.03972436154061154)), (2038, np.float64(0.03969164245066942)), (669, np.float64(0.03966100001658246)), (2840, np.float64(0.03965935895693759)), (1486, np.float64(0.039513174360582076)), (3399, np.float64(0.03945927059842434)), (1027, np.float64(0.0393242869278138)), (3, np.float64(0.03926881658956743)), (489, np.float64(0.03910881916216053)), (1311, np.float64(0.03905015473005006)), (3259, np.float64(0.03902673492141717)), (3035, np.float64(0.03900731605856505)), (2951, np.float64(0.03898266079633895)), (1933, np.float64(0.03892209801056158)), (441, np.float64(0.03888359658087731)), (1095, np.float64(0.038861370177131364)), (2781, np.float64(0.03881930823549028)), (1340, np.float64(0.03866388157068037)), (511, np.float64(0.038629531655452416)), (3049, np.float64(0.038534662756374044)), (2571, np.float64(0.03850107944115179)), (2810, np.float64(0.03849271375488443)), (2208, np.float64(0.03835366221425907)), (3975, np.float64(0.03831110680191552)), (4638, np.float64(0.038244768434298006)), (604, np.float64(0.038182033160445494)), (4226, np.float64(0.038094362569670706)), (4300, np.float64(0.0380848703530985)), (1077, np.float64(0.038055773551673944)), (2688, np.float64(0.03794756068694474)), (2600, np.float64(0.03791028483100921)), (2, np.float64(0.03789625003894503)), (637, np.float64(0.03788744219421832)), (3533, np.float64(0.03788709579470746)), (1607, np.float64(0.03783677059405956)), (1829, np.float64(0.037825761951613024)), (1881, np.float64(0.037732464463242785)), (3877, np.float64(0.03768262876389997)), (21, np.float64(0.03766256181791601)), (4360, np.float64(0.03756029460695861)), (1474, np.float64(0.03754664255048531)), (610, np.float64(0.03751306495621514)), (2213, np.float64(0.03744843664558144)), (622, np.float64(0.0374120196246551)), (1058, np.float64(0.03732554701078354)), (4205, np.float64(0.037296400818523985)), (3199, np.float64(0.03718664575906763)), (1355, np.float64(0.03710221671030567)), (1372, np.float64(0.03707442922836613)), (4292, np.float64(0.03706833370445441)), (4401, np.float64(0.03706787724271612)), (3520, np.float64(0.03688822335416765)), (555, np.float64(0.036874317986106325)), (4733, np.float64(0.03683355073661511)), (807, np.float64(0.03665880999352451)), (818, np.float64(0.03660409918442853)), (1557, np.float64(0.03644666100378192)), (46, np.float64(0.03644264125248525)), (3692, np.float64(0.0363283729997409)), (3454, np.float64(0.03628074258466031)), (4000, np.float64(0.03625485551894298)), (177, np.float64(0.03623395709591594)), (1073, np.float64(0.03622856401260146)), (605, np.float64(0.03620606968895601)), (4089, np.float64(0.03618420925085034)), (405, np.float64(0.03616918076041602)), (2221, np.float64(0.03611039923596645)), (65, np.float64(0.03586104197455195)), (553, np.float64(0.03583397478479647)), (2704, np.float64(0.03583164973729769)), (1838, np.float64(0.03571892206708558)), (367, np.float64(0.03568818038975273)), (2809, np.float64(0.03563238807942046)), (3842, np.float6

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you :  \n ')

i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movie_dataset[movie_dataset.index==index]['title'].values[0]
  if (i<31):
    print(i , '.' , title_from_index)
    i+=1

Movies suggested for you :

1 . Street Kings
2 . Black Rain
3 . End of Watch
4 . Dick Tracy
5 . Gangster Squad
6 . Freedom Writers
7 . Lies in Plain Sight
8 . S.W.A.T.
9 . Phone Booth
10 . Glory
11 . Money Talks
12 . River's Edge
13 . Sabotage
14 . Panic Room
15 . Harley Davidson and the Marlboro Man
16 . Cellular
17 . Malibu's Most Wanted
18 . National Lampoon's Loaded Weapon 1
19 . Ladder 49
20 . Training Day
21 . Light It Up
22 . The Great Debaters
23 . Southpaw
24 . Vantage Point
25 . The Train
26 . Stealing Harvard
27 . The Watcher
28 . The Fast and the Furious
29 . Dead Poets Society
30 . The French Connection

# Movie Recommendation System

In [ ]:
# Getting the movie name from user
movie_name = input("Enter your Favourite movie name")
# Creating the list with all the movie names given in the dataset
list_all_of_the_titles = movie_dataset['title'].tolist()
# finding the close match for the movie name given  by the user
find_close_match = difflib.get_close_matches(movie_name, list_all_of_the_titles)
close_match = find_close_match[0]
#find the index of the movie with title
index_of_the_movie = movie_dataset[movie_dataset.title == close_match]['index'].values[0]
#getting the list of similar movies
similarity_score  = list(enumerate(similarity[index_of_the_movie]))
# Sorting the movies base on their similarity score
sorted_similar_movies = sorted(similarity_score , key = lambda x:x[1] , reverse = True)
# print the name of similar movies based on the index
print('Movies suggested for you :  \n ')

i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movie_dataset[movie_dataset.index==index]['title'].values[0]
  if (i<31):
    print(i , '.' , title_from_index)
    i+=1

Enter your Favourite movie namelost in space
Movies suggested for you :

1 . Lost in Space
2 . Say It Isn't So
3 . Hot Tub Time Machine 2
4 . Titan A.E.
5 . Hot Tub Time Machine
6 . Alien
7 . Men in Black 3
8 . Crimson Tide
9 . Austin Powers: The Spy Who Shagged Me
10 . The Helix... Loaded
11 . Dawn of the Planet of the Apes
12 . Star Trek
13 . One True Thing
14 . Mission to Mars
15 . Dracula
16 . Austin Powers: International Man of Mystery
17 . Space Cowboys
18 . The Book of Eli
19 . Avatar
20 . Muppets from Space
21 . Galaxina
22 . Dumb and Dumberer: When Harry Met Lloyd
23 . Captive
24 . Time Changer
25 . The Astronaut's Wife
26 . Planet 51
27 . Bill & Ted's Bogus Journey
28 . After Earth
29 . From Hell
30 . The Host