#Two categories are present in the current used dataset
###1: Spam Mail __ Spam mail__ 0
###2:  Ham Mail__ Normal Mail__ 1

# Import Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer # convert data textual into numerical data so model can undersrtand it -- Features are numerical numbers
from sklearn.metrics import accuracy_score

# Import the Data

In [3]:
mail_dataset = pd.read_csv("/content/mail_data.csv")

In [4]:
mail_dataset.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

# Data Preprocessing

In [6]:
# Check the number of rows and columns
mail_dataset.shape

(5572, 2)

In [7]:
# information about the dataset
mail_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [10]:
# Checking the missing values
mail_dataset.isnull().sum()

Category    0
Message     0
dtype: int64

In [11]:
# Replace the null values
mail_dataset = mail_dataset.where((pd.notnull(mail_dataset)) , '')

# Ham -- 1
# Spam -- 0

# Labelling the Mail Dataset --- Label Encoding

In [12]:
#label spam mail as 0;  ham mail as 1 ;
mail_dataset.loc[mail_dataset['Category'] == 'spam' , 'Category'] = 0
mail_dataset.loc[mail_dataset['Category'] == 'ham' , 'Category'] = 1

In [14]:
print(mail_dataset.head())

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

In [15]:
# Separating the data as texts and Label -- so we can feed this data to model
X = mail_dataset['Message']
y = mail_dataset['Category']

In [16]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [17]:
print(y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [19]:
# Splitting the data in Training or Testing data
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state=42)

 ### Printing the shape of the dataset

In [24]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(5572,)
(4457,)
(1115,)

# Feature Extraction

In [27]:
 # Text data into numerical data --
 # word score less then 1 then ignore it -- mf_df = 1
 # stop words -- repeated multiple time  a , at , the  -- ignore them
 # lowercase = True  all the words will be convert in lowercase
feature_extraction = TfidfVectorizer(min_df= 1 , stop_words='english' , lowercase=True)

In [31]:
X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

# convert y_train  and y_test values as  integers
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [32]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34840 stored elements and shape (4457, 7440)>
  Coords	Values
  (0, 5512)	0.1898892037332199
  (0, 7222)	0.2173884735352799
  (0, 258)	0.2379428657041507
  (0, 7162)	0.2550284465664535
  (0, 354)	0.3544175987866074
  (0, 2724)	0.3544175987866074
  (0, 7300)	0.24288153842988894
  (0, 2049)	0.3034375179183143
  (0, 3262)	0.33791755486732394
  (0, 5800)	0.17558937755823417
  (0, 6264)	0.1898892037332199
  (0, 694)	0.3171299579602537
  (0, 2497)	0.2442158912653505
  (0, 5818)	0.22682143517864364
  (1, 3267)	0.26787130770292167
  (1, 6109)	0.32397626344658004
  (1, 6738)	0.28986069568917994
  (1, 2335)	0.21623212751660786
  (1, 5650)	0.3604441444703179
  (1, 3333)	0.20665394084233094
  (1, 2440)	0.3387054464839871
  (1, 4509)	0.40282459910606705
  (1, 3932)	0.24325511357721422
  (1, 3804)	0.19029023465152678
  (1, 2555)	0.3840709491751003
  :	:
  (4452, 3084)	0.22948428918295163
  (4452, 3290)	0.26370969643076225
  (4452, 3978)	0.4574160733416501
  (4452, 7280)	0.3968991650168732
  (4452, 2438)	0.4574160733416501
  (4452, 7264)	0.479751063610169
  (4453, 6108)	0.5975612693457145
  (4453, 4004)	0.5244851817485772
  (4453, 3874)	0.6064947019588055
  (4454, 2893)	0.38087861810984514
  (4454, 3249)	0.3182708584577292
  (4454, 5409)	0.4079234999314281
  (4454, 5149)	0.43410473161397095
  (4454, 6114)	0.4465347909835087
  (4454, 6113)	0.4465347909835087
  (4455, 6686)	0.40745931976870786
  (4455, 4660)	0.4924788339394118
  (4455, 3691)	0.5541750775894743
  (4455, 5815)	0.5332274226200294
  (4456, 3720)	0.24023610815826443
  (4456, 2236)	0.3138975170542533
  (4456, 5719)	0.32762879958318814
  (4456, 6467)	0.4816862839263015
  (4456, 6078)	0.4654515925066416
  (4456, 4518)	0.5364209818026567

In [33]:
print(y_train)

1978    0
3989    1
3935    1
4078    1
4086    0
       ..
3772    1
5191    1
5226    1
5390    1
860     1
Name: Category, Length: 4457, dtype: int64

# Calling the Machine Learning Model

In [35]:
model = LogisticRegression()

# Training the Logistic Regression model with Training data

In [36]:
model.fit(X_train_features , y_train)

LogisticRegression()

# Evaluating the model on the training data

In [46]:
# Prediction on training data
prediction_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(y_train , prediction_on_training_data)

In [45]:
print("Accuracy on Training data : " , accuracy_on_training_data)

Accuracy on Training data :  0.9670181736594121

# Evaluating the model on the testing data

In [44]:
#Prediction on testing data
prediction_on_testing_data = model.predict(X_test_features)
accuracy_on_test_data = accuracy_score(y_test , prediction_on_testing_data)

In [43]:
print(accuracy_on_test_data)

0.967713004484305

# Building a Predictive model

In [52]:
input_mail = ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]
# convert text to fetaure vector
input_data_features = feature_extraction.transform(input_mail)
# making predictions
predictions = model.predict(input_data_features)
print(predictions)

if (predictions[0] == 1):
  print("Ham Mail")
else:
  print("Spam Mail")

[0]
Spam Mail